Fix insufficient balance error
There was a flaw in logic which allowed to bypass a check for minimal
allowed order size. As a result, worker tried to place too small order
causing an error `bitsharesapi.exceptions.UnhandledRPCError: Assert
Exception: d.get_balance( *_seller, *_sell_asset ) >= op.amount_to_sell:
insufficient balance`

Closes: #649